logging:
  level:
    org:
      springframework: info
  config: classpath:logback.xml


spring:
  datasource:
    username: root
    password: Br00k51d3
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/bookmarks

  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

    defer-datasource-initialization: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false

  application:
    name: bookmarks-api
  config:
    activate:
      on-profile:


server:
  port: 8080
